[package]
name = "pong-bevy"
version = "0.1.0"
authors = ["mverardo <mauricio.verardo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
